
name: Publish Extension

on:
  pull_request:
   
jobs:
  publish-extension:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: setup vsce
        run: npm install -g @vscode/vsce
      
      - name: generate package
        run: vsce package
      
      - name: Publish
        if: success()
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      
 