
name: Publish Extension

on:
  push:
    branches:
    - main
   
jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Setup vsce
        run: npm install -g @vscode/vsce
      
      - name: Generate package
        run: npm install && vsce package
      
      - name: Publish
        if: success()
        run: yarn install && npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
  
      - name: Send message to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
